sudo: true
language: node_js
node_js:
  - "9"
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
    - server/static/node_modules
    - packages/app-extensions-browser/node_modules
    - packages/entity-browser/node_modules
    - packages/entity-detail/node_modules
    - packages/entity-list/node_modules
    - packages/login/node_modules
    - packages/merge/node_modules
    - packages/resource-scheduler/node_modules
    - packages/scheduler/node_modules
    - packages/simple-form/node_modules
    - packages/tocco-test-util/node_modules
    - packages/tocco-theme/node_modules
    - packages/tocco-ui/node_modules
    - packages/tocco-util/node_modules
    - .eslintcache
    - .jestcache

install:
  - yarn setup
  - travis_wait lerna bootstrap --concurrency=1 --mutex network

script:
  - npm run lint
  - jest --maxWorkers=4 --silent --verbose false
  - BACKEND=https://master.tocco.ch yarn build-storybook

after_success:
  - npm run codecov;
  - if [ ${TRAVIS_EVENT_TYPE} != "cron" ]; then
        bash deployment/deploy_storybook.sh;
    fi
  - bash deployment/storybook_link.sh;

env:
  global:
  - ENCRYPTION_LABEL: "49dedc788d53"
  - COMMIT_AUTHOR_EMAIL: "bot@tocco.ch"
