sudo: true
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules
    - packages/tocco-ui/node_modules
    - packages/tocco-ui-showcase/node_modules
    - packages/tocco-ui-util/node_modules
    - packages/tocco-prototype/node_modules
    - packages/action-merge/node_modules
    - packages/action-password-update/node_modules

install:
  - npm list -g lerna â€“depth=0 || npm install -g lerna@2.0.0-beta.28
  - npm install
  - lerna bootstrap

script:
  - npm run lint
  - npm run test

after_success:
  - bash deployment/deploy_showcase.sh

env:
  global:
  - ENCRYPTION_LABEL: "49dedc788d53"
  - COMMIT_AUTHOR_EMAIL: "bot@tocco.ch"
